CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "course_id" int NOT NULL  ,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level" varchar(20) NOT NULL,
  "teacher" varchar NOT NULL,
  PRIMARY KEY ("id", "course_id")
);

CREATE TABLE "Course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "users_Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "course_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "categories_id" int NOT NULL
);

ALTER TABLE "Courses" ADD FOREIGN KEY ("course_id") REFERENCES "Course" ("id");

ALTER TABLE "users_Courses" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "users_Courses" ADD FOREIGN KEY ("courses_id") REFERENCES "Course" ("id");

ALTER TABLE "course_categories" ADD FOREIGN KEY ("course_id") REFERENCES "Course" ("id");

ALTER TABLE "course_categories" ADD FOREIGN KEY ("categories_id") REFERENCES "Categories" ("id");
